### ISSUE TITLE
编译不通过

### ISSUE THREAD

**Issue by creatn** [WelkinXie/AESCipher-iOS#1]
我准备把集成到我的项目中，使用的时候，编译无法通过，是还需要配置什么么？

**Comment by WelkinXie** [comment]
我这边测试了直接集成是没有问题的，能否提供一些错误信息呢？？

**Comment by shangguan16** [comment]
这边加密完以后做压缩，添加 libbz2.1.0.dylib,做了压缩解压缩，然后编译不过去

**Comment by WelkinXie** [comment]
能否截个图看看编译错误提示的信息是什么？感觉应该是导入 libbz2.1.0.dylib 而导致的错误。你试试把我这个库的代码文件移除了应该也是编译不过的。

**Comment by shangguan16** [comment]
![2016-08-24 11 17 50](https://cloud.githubusercontent.com/assets/21188680/17917164/729415aa-69ec-11e6-8d83-20cfaec0db6c.png)

**Comment by WelkinXie** [comment]
明显报错的是 LFCGzipUtility 这个库哦，去 project 的 Linked Frameworks and Libraries 里面添加 libz.tbd 吧。跟我这个代码没关系的。
