### ISSUE TITLE
代码默认的加密方式是什么呢？ 我想把加密过的内容 在线解密下，不知道怎么配置

### ISSUE THREAD

**Issue by oscar608** [WelkinXie/AESCipher-iOS#6]
![image](https://user-images.githubusercontent.com/10752360/44440433-9ed58300-a5fa-11e8-9b8e-b74e92694ef2.png)

**Comment by WelkinXie** [comment]
加密模式 CBC
填充 PKCS7Padding
数据块 128bit
偏移量 "A-16-Byte-String"
base64、utf8
