### ISSUE TITLE
How can I achieve the same encryption with CBC mode

### ISSUE THREAD

**Issue by iosdevgautam** [WelkinXie/AESCipher-iOS#7]
Actually I am trying to achieve the encryption for iOS same as given in this link: **https://gist.github.com/demisang/716250080d77a7f65e66f4e813e5a636**

Your code is working fine. But the data I am getting encrypted from the android side implemented on above link encryption. I am getting nil all the time on decryption.

Can you please help me to do that? I have been looking for solutions for longtime.

**Comment by WelkinXie** [comment]
The iv of the solution in the link is different from mine. Just make them the same, or simply use my code [https://github.com/WelkinXie/AESCipher-Java](https://github.com/WelkinXie/AESCipher-Java) for java(android) .
