### ISSUE TITLE
free(operationBytes);不会执行

### ISSUE THREAD

**Issue by ChenZeBin** [WelkinXie/AESCipher-iOS#8]
if (cryptStatus == kCCSuccess) {
// 这个return后，下面的free就不会执行了
        return [NSData dataWithBytesNoCopy:operationBytes length:actualOutSize];
    }
    free(operationBytes);
    operationBytes = NULL;
    return nil;

**Comment by WelkinXie** [comment]
调用 dataWithBytesNoCopy 后不需要 free，原因参见苹果文档
